/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingCreatorRouteImport } from './routes/onboarding.creator'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding.brand'
import { Route as DashboardCreatorRouteImport } from './routes/dashboard.creator'
import { Route as DashboardBrandRouteImport } from './routes/dashboard.brand'
import { Route as CreatorCreatorIdRouteImport } from './routes/creator.$creatorId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthChooseRoleRouteImport } from './routes/auth.choose-role'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreatorRoute = OnboardingCreatorRouteImport.update({
  id: '/onboarding/creator',
  path: '/onboarding/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({
  id: '/onboarding/brand',
  path: '/onboarding/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreatorRoute = DashboardCreatorRouteImport.update({
  id: '/dashboard/creator',
  path: '/dashboard/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBrandRoute = DashboardBrandRouteImport.update({
  id: '/dashboard/brand',
  path: '/dashboard/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCreatorIdRoute = CreatorCreatorIdRouteImport.update({
  id: '/creator/$creatorId',
  path: '/creator/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChooseRoleRoute = AuthChooseRoleRouteImport.update({
  id: '/auth/choose-role',
  path: '/auth/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/inbox': typeof InboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/choose-role': typeof AuthChooseRoleRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/dashboard/brand': typeof DashboardBrandRoute
  '/dashboard/creator': typeof DashboardCreatorRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/inbox': typeof InboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/choose-role': typeof AuthChooseRoleRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/dashboard/brand': typeof DashboardBrandRoute
  '/dashboard/creator': typeof DashboardCreatorRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/inbox': typeof InboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/choose-role': typeof AuthChooseRoleRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/dashboard/brand': typeof DashboardBrandRoute
  '/dashboard/creator': typeof DashboardCreatorRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/inbox'
    | '/auth/callback'
    | '/auth/choose-role'
    | '/auth/login'
    | '/auth/signup'
    | '/creator/$creatorId'
    | '/dashboard/brand'
    | '/dashboard/creator'
    | '/onboarding/brand'
    | '/onboarding/creator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/inbox'
    | '/auth/callback'
    | '/auth/choose-role'
    | '/auth/login'
    | '/auth/signup'
    | '/creator/$creatorId'
    | '/dashboard/brand'
    | '/dashboard/creator'
    | '/onboarding/brand'
    | '/onboarding/creator'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/inbox'
    | '/auth/callback'
    | '/auth/choose-role'
    | '/auth/login'
    | '/auth/signup'
    | '/creator/$creatorId'
    | '/dashboard/brand'
    | '/dashboard/creator'
    | '/onboarding/brand'
    | '/onboarding/creator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  InboxRoute: typeof InboxRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthChooseRoleRoute: typeof AuthChooseRoleRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CreatorCreatorIdRoute: typeof CreatorCreatorIdRoute
  DashboardBrandRoute: typeof DashboardBrandRoute
  DashboardCreatorRoute: typeof DashboardCreatorRoute
  OnboardingBrandRoute: typeof OnboardingBrandRoute
  OnboardingCreatorRoute: typeof OnboardingCreatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/creator': {
      id: '/onboarding/creator'
      path: '/onboarding/creator'
      fullPath: '/onboarding/creator'
      preLoaderRoute: typeof OnboardingCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/brand': {
      id: '/onboarding/brand'
      path: '/onboarding/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof OnboardingBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator': {
      id: '/dashboard/creator'
      path: '/dashboard/creator'
      fullPath: '/dashboard/creator'
      preLoaderRoute: typeof DashboardCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/brand': {
      id: '/dashboard/brand'
      path: '/dashboard/brand'
      fullPath: '/dashboard/brand'
      preLoaderRoute: typeof DashboardBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$creatorId': {
      id: '/creator/$creatorId'
      path: '/creator/$creatorId'
      fullPath: '/creator/$creatorId'
      preLoaderRoute: typeof CreatorCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/choose-role': {
      id: '/auth/choose-role'
      path: '/auth/choose-role'
      fullPath: '/auth/choose-role'
      preLoaderRoute: typeof AuthChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  InboxRoute: InboxRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthChooseRoleRoute: AuthChooseRoleRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CreatorCreatorIdRoute: CreatorCreatorIdRoute,
  DashboardBrandRoute: DashboardBrandRoute,
  DashboardCreatorRoute: DashboardCreatorRoute,
  OnboardingBrandRoute: OnboardingBrandRoute,
  OnboardingCreatorRoute: OnboardingCreatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
